### PR TITLE
Feature

### PR DESCRIPTION
**Pull request by RodolfoRodriguezMata**

### CODE REVIEW

**Review by Forison — COMMENTED** [review]
#### Pull request under review by Addo

**Review by Forison — CHANGES_REQUESTED** [review]
# Hi @RodolfoRodriguezMata 🙂
you have done a great job so far.
Here is a change we have to do to get this project approved.
* [ ] It contains four elements which are links (to another articles or #)🙂. Currently, each image in ```.below``` is not behaving as a link.
####  [optional ] 
- You may add a hover effect to your nav-links.🙂
- You may improve semantic Html by wrapping the ```div``` after the ```nav`` and the ```.below``` class section in a ```main```  tag 🙂
### Kindly make this change and submit the project for review;🙂
feel free to contact me on [LinkedIn](https://www.linkedin.com/in/forison-addo-558201159/), [Twitter](https://twitter.com/ADDOBOAKYE1) or slack for further clarification if necessary. I would be happy to assist you.

Happy coding.🙂

**Review by Redvanisation — APPROVED** [review]
# Project approved ✔️ 

### Hello @RodolfoRodriguezMata  🌟 

### _Nice work on this project, it seems that you have met the requirements so I am approving your project. 👍_ 

### You may merge to master and submit a project completion form. 🚀 

### Good luck! 🍀

**Comment by RodolfoRodriguezMata** [comment]
Thank you very much for your feedback and help :)

**Pull request merged**
